services:
  # Main proxy container
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.7.1-alpine
    container_name: nginx-proxy
    restart: always
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    ports:
      - 80:80
      - 443:443
    volumes:
      - "${DATA_DIR}/nginx/certs:/etc/nginx/certs"
      - "${DATA_DIR}/nginx/vhosts:/etc/nginx/vhost.d"
      - "${DATA_DIR}/nginx/html:/usr/share/nginx/html"
      - "${DATA_DIR}/nginx/htpasswd:/etc/nginx/htpasswd"
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.conf:/etc/nginx/proxy.conf

  # Letsencrypt companion container
  acme-companion:
    image: nginxproxy/acme-companion:2.6.0
    container_name: acme-companion
    restart: always
    volumes:
      - "${DATA_DIR}/nginx/certs:/etc/nginx/certs"
      - "${DATA_DIR}/nginx/vhosts:/etc/nginx/vhost.d"
      - "${DATA_DIR}/nginx/html:/usr/share/nginx/html"
      - "${DATA_DIR}/nginx/acme:/etc/acme.sh"
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./nginx.conf:/etc/nginx/proxy.conf
    environment: 
      DEFAULT_EMAIL: ${DOMAIN_ADMIN_EMAIL}
    depends_on:
      - nginx-proxy

  # CAdvisor container
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.52.1
    container_name: cadvisor
    restart: unless-stopped
    hostname: 
      cadvisor
    devices:
      - /dev/kmsg
    ipc: shareable
    privileged: true
    command:
      - '-housekeeping_interval=20s'
      - '-store_container_labels=false'
      - '-docker_only=true'
    security_opt:
      - label=disable
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /etc/machine-id:/etc/machine-id:ro

  # Node-Exporter container
  node-exporter:
    image: prom/node-exporter:v1.9.1
    container_name: node-exporter
    restart: unless-stopped
    hostname: 
      node-exporter
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --path.rootfs=/host
      - --collector.filesystem.ignored-mount-points
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /:/host:ro,rslave

  # BlackBox exporter container
  blackbox-exporter:
    image: prom/blackbox-exporter:v0.27.0
    container_name: blackbox-exporter
    restart: unless-stopped
    hostname: 
      blackbox-exporter
    command:
      - '--config.file=/config/blackbox.yml'
    volumes:
      - "./blackbox-exporter:/config"

  # Prometheus container
  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: prometheus
    restart: unless-stopped
    hostname: 
      prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=10d'
    volumes:
      - "./prometheus:/etc/prometheus"
      - "${MONITORING_DATA_DIR}/prometheus/data:/prometheus"
    links:
      - cadvisor:cadvisor
      - node-exporter:node-exporter
    depends_on:
      - cadvisor
      - node-exporter
      - blackbox-exporter

# Root container
  nginx:
    image: nginx:alpine-slim
    container_name: nginx
    restart: always
    volumes:
      - "./dashboard:/usr/share/nginx/html"
    environment:
      VIRTUAL_HOST: ${ROOT_HOST},www.${ROOT_HOST}
      LETSENCRYPT_HOST: ${ROOT_HOST},www.${ROOT_HOST}
    depends_on:
      - acme-companion

  # Loki container for logs
  loki:
    image: grafana/loki:3.5.2
    container_name: loki
    restart: always
    expose:
      - "3100"
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/loki-config.yaml
      - ${MONITORING_DATA_DIR}/loki:/var/lib/loki
    command: -config.file=/etc/loki/loki-config.yaml

  # Promtail container for logs aggregation
  promtail:
    image: grafana/promtail:3.5.2
    container_name: promtail
    restart: always
    volumes:
      - ./loki/promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: -config.file=/etc/promtail/promtail-config.yaml
    depends_on:
      - loki

  # Dozzle container
  dozzle:
    image: amir20/dozzle:v8.13.7
    container_name: dozzle
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - "${DATA_DIR}/dozzle:/data"
    environment:
      DOZZLE_AUTH_PROVIDER: simple
      DOZZLE_AUTH_TTL: 48h
      VIRTUAL_HOST: dozzle.${ROOT_HOST}
      LETSENCRYPT_HOST: dozzle.${ROOT_HOST}
      VIRTUAL_PORT: 8080
    depends_on:
      - acme-companion
  
  # Grafana container
  grafana:
    image: grafana/grafana:12.0.2
    container_name: grafana
    restart: always
    volumes:
      - "${MONITORING_DATA_DIR}/grafana/storage:/var/lib/grafana"
      - "${MONITORING_DATA_DIR}/grafana/provisioning:/etc/grafana/provisioning"
    links:
      - prometheus:prometheus
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      VIRTUAL_HOST: grafana.${ROOT_HOST}
      LETSENCRYPT_HOST: grafana.${ROOT_HOST}
      VIRTUAL_PORT: 3000
    depends_on:
      - prometheus 
      - loki
      - acme-companion

  # QBittorrent container
  qbittorrent:
    image: linuxserver/qbittorrent:5.1.2
    container_name: qbittorrent
    restart: always
    hostname:
      qbittorrent.${ROOT_HOST}
    ports:
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - "${DATA_DIR}/qbittorrent/data:/config"
      - "${PLEX_MEDIA_DIR}/downloads:/downloads"
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Sofia
      WEBUI_PORT: 8080
      TORRENTING_PORT: 6881
      VIRTUAL_HOST: qbittorrent.${ROOT_HOST}
      LETSENCRYPT_HOST: qbittorrent.${ROOT_HOST}
      VIRTUAL_PORT: 8080
    depends_on:
      - acme-companion

  # Files Browser container
  files:
    image: filebrowser/filebrowser:v2.40.2
    container_name: files
    restart: always
    hostname:
      files.${ROOT_HOST}
    volumes:
      - "${DATA_DIR}/filebrowser/data/filebrowser.db:/database/filebrowser.db"
      - "${PLEX_MEDIA_DIR}:/srv"
    command:
      - '--database'
      - '/database/filebrowser.db'
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Sofia
      VIRTUAL_HOST: files.${ROOT_HOST}
      LETSENCRYPT_HOST: files.${ROOT_HOST}
      VIRTUAL_PORT: 80
    depends_on:
      - acme-companion

  # Plex container
  plex:
    image: linuxserver/plex:1.41.9
    container_name: plex
    restart: always
    hostname:
      plex.${ROOT_HOST}
    volumes:
      - "${DATA_DIR}/plex:/config"
      - "${PLEX_MEDIA_DIR}:/media"
    ports:
      - 32400:32400
    environment:
      PUID: 1000
      PGID: 1000
      VERSION: docker
      PLEX_CLAIM: ${PLEX_CLAIM_TOKEN}
      VIRTUAL_HOST: plex.${ROOT_HOST}
      LETSENCRYPT_HOST: plex.${ROOT_HOST}
      VIRTUAL_PORT: 32400
    devices:
      - /dev/dri:/dev/dri
    depends_on:
      - acme-companion

  # Calibre container
  calibre:
    image: linuxserver/calibre:8.7.0
    container_name: calibre
    restart: always
    hostname:
      calibre.${ROOT_HOST}
    volumes:
      - "${DATA_DIR}/calibre:/config"
    ports:
      - 8080:8080
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Sofia
      PASSWORD: ${CALIBRE_ADMIN_PWD}
      VIRTUAL_HOST: calibre.${ROOT_HOST}
      LETSENCRYPT_HOST: calibre.${ROOT_HOST}
      VIRTUAL_PORT: 8081
    depends_on:
      - acme-companion

  # Postgres DB container for Mealie
  mealiedb:
    image: postgres:17.5-alpine3.20
    container_name: mealiedb
    restart: always
    expose:
      - "${MEALIE_DB_PORT}" 
    volumes:
      - "${DATA_DIR}/mealiedb:/var/lib/postgresql/data"
    environment: 
      POSTGRES_DB: ${MEALIE_DB_NAME}
      POSTGRES_USER: ${MEALIE_DB_USER}
      POSTGRES_PASSWORD: ${MEALIE_DB_PASSWORD}
    command: ["-p", "${MEALIE_DB_PORT}"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${MEALIE_DB_USER} -p ${MEALIE_DB_PORT}"]
      interval: 3s
      timeout: 1s
      retries: 10
    depends_on:
      - acme-companion

  # Mealie container
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.0.1
    container_name: mealie
    restart: always
    deploy:
      resources:
        limits:
          memory: 1000M 
    hostname:
      mealie.${ROOT_HOST}
    volumes:
      - "${DATA_DIR}/mealie:/app/data"
    environment:
      DB_ENGINE: postgres
      POSTGRES_USER: ${MEALIE_DB_USER}
      POSTGRES_PASSWORD: ${MEALIE_DB_PASSWORD}
      POSTGRES_SERVER: mealiedb
      POSTGRES_PORT: ${MEALIE_DB_PORT}
      POSTGRES_DB: ${MEALIE_DB_NAME}
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: Europe/Sofia
      BASE_URL: https://mealie.${ROOT_HOST}
      VIRTUAL_HOST: mealie.${ROOT_HOST}
      LETSENCRYPT_HOST: mealie.${ROOT_HOST}
      VIRTUAL_PORT: 9000
    depends_on:
      - mealiedb

  # FreshRSS container
  freshrss:
    image: linuxserver/freshrss:1.26.3
    container_name: freshrss
    restart: always
    hostname:
      freshrss.${ROOT_HOST}
    volumes:
      - "${DATA_DIR}/freshrss:/config"
    environment:
      UID: 1000
      GID: 1000
      TZ: Europe/Sofia
      VIRTUAL_HOST: freshrss.${ROOT_HOST}
      LETSENCRYPT_HOST: freshrss.${ROOT_HOST}
      VIRTUAL_PORT: 80
    depends_on:
      - acme-companion
  
  # Stirling PDF container
  stirling:
    image: stirlingtools/stirling-pdf:1.0.2
    container_name: stirling
    restart: always
    hostname:
      stirling.${ROOT_HOST}
    volumes:
      - "${DATA_DIR}/stirling/trainingData:/usr/share/tessdata"
      - "${DATA_DIR}/stirling/extraConfigs:/configs"
      - "${DATA_DIR}/stirling/customFiles:/customFiles"
      - "${DATA_DIR}/stirling/logs:/logs"
      - "${DATA_DIR}/stirling/pipeline:/pipeline"
    environment:
      DOCKER_ENABLE_SECURITY: true
      SECURITY_ENABLELOGIN: true
      LANGS: en_GB
      VIRTUAL_HOST: stirling.${ROOT_HOST}
      LETSENCRYPT_HOST: stirling.${ROOT_HOST}
      VIRTUAL_PORT: 8080
    depends_on:
      - acme-companion
  
  # YouTrack container
  youtrack:
    image: jetbrains/youtrack:2025.2.87963
    container_name: youtrack
    restart: always
    hostname:
      youtrack.${ROOT_HOST}
    volumes:
      - "${DATA_DIR}/youtrack/data:/opt/youtrack/data"
      - "${DATA_DIR}/youtrack/conf:/opt/youtrack/conf"
      - "${DATA_DIR}/youtrack/logs:/opt/youtrack/logs"
      - "${DATA_DIR}/youtrack/backups:/opt/youtrack/backups"
    environment:
      VIRTUAL_HOST: youtrack.${ROOT_HOST}
      LETSENCRYPT_HOST: youtrack.${ROOT_HOST}
      VIRTUAL_PORT: 8080
    depends_on:
      - acme-companion

  # PiHole container
  pihole:
    image: pihole/pihole:2025.07.1
    container_name: pihole
    restart: always
    hostname:
      pihole.${ROOT_HOST}
    volumes:
      - "${MONITORING_DATA_DIR}/pihole/etc_pihole:/etc/pihole"
      - "${MONITORING_DATA_DIR}/pihole/etc_dnsmasq.d:/etc/dnsmasq.d"
    ports:
      - "${ROOT_IP}:53:53/tcp"
      - "${ROOT_IP}:53:53/udp"
    environment:
      TZ: Europe/Sofia
      FTLCONF_webserver_api_password: ${PIHOLE_PASSWORD}
      FTLCONF_dns_listeningMode: all
      VIRTUAL_HOST: pihole.${ROOT_HOST}
      LETSENCRYPT_HOST: pihole.${ROOT_HOST}
      VIRTUAL_PORT: 80
    depends_on:
      - acme-companion

  # VPN wireguard container
  wireguard:
    image: ghcr.io/wg-easy/wg-easy:15
    container_name: wireguard
    restart: unless-stopped
    hostname:
      vpn.${ROOT_HOST}
    volumes:
      - "${DATA_DIR}/wireguard:/etc/wireguard"
      - "/lib/modules:/lib/modules:ro"
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    environment:
      INSECURE: true
      VIRTUAL_HOST: vpn.${ROOT_HOST}
      LETSENCRYPT_HOST: vpn.${ROOT_HOST}
      VIRTUAL_PORT: 51821
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1
    depends_on:
      - acme-companion

  # Postgres DB container for Keycloak
  keycloakdb:
    image: postgres:17.5-alpine3.20
    container_name: keycloakdb
    restart: always
    expose:
      - "5432" 
    volumes:
      - "${DATA_DIR}/keycloakdb:/var/lib/postgresql/data"
    environment: 
      POSTGRES_DB: ${KEYCLOAK_DB_NAME}
      POSTGRES_USER: ${KEYCLOAK_DB_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${KEYCLOAK_DB_USER}"]
      interval: 3s
      timeout: 1s
      retries: 10
    depends_on:
      - acme-companion

  # Keycloak container
  keycloak:
    image: keycloak/keycloak:26.3.1
    container_name: keycloak
    restart: always
    links:
      - keycloakdb:keycloakdb
    command:
      - 'start'
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloakdb/${KEYCLOAK_DB_NAME}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_DB_SCHEMA: public
      KC_HOSTNAME: auth.${ROOT_HOST}
      KC_HTTP_ENABLED: true
      KC_PROXY_HEADERS: xforwarded
      PROXY_ADDRESS_FORWARDING: true
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      LETSENCRYPT_HOST: auth.${ROOT_HOST}
      VIRTUAL_HOST: auth.${ROOT_HOST}
      VIRTUAL_PORT: 8080
    healthcheck:
      test: cat /proc/net/tcp6 | grep '00000000000000000000000000000000:1F90 00000000000000000000000000000000:0000' || exit 1
      interval: 5s
      timeout: 2s
      retries: 60
      start_period: 400s
    depends_on:
      keycloakdb:
          condition: service_healthy

  # InvVal container
  invval:
    image: dzahariev/invval:3.6
    container_name: invval
    restart: always
    hostname:
      invval.${ROOT_HOST}
    environment:
      PUID: 1000
      PGID: 1000
      KEYCLOAK_URL: https://auth.${ROOT_HOST} 
      REALM: ${INVVAL_REALM}
      CLIENT_ID: ${INVVAL_CLIENT_ID}
      CLIENT_SECRET: ${INVVAL_CLIENT_SECRET} 
      BASE_URL: https://invval.${ROOT_HOST}
      TZ: Europe/Sofia
      VIRTUAL_HOST: invval.${ROOT_HOST}
      LETSENCRYPT_HOST: invval.${ROOT_HOST}
      VIRTUAL_PORT: 8080
    depends_on:
      keycloak:
        condition: service_healthy

  # Postgres DB container for Domo
  domodb:
    image: postgres:17.5-alpine3.20
    container_name: domodb
    restart: always
    expose:
      - "${DOMO_DB_PORT}" 
    volumes:
      - "${DATA_DIR}/domodb:/var/lib/postgresql/data"
    environment: 
      POSTGRES_DB: ${DOMO_DB_NAME}
      POSTGRES_USER: ${DOMO_DB_USER}
      POSTGRES_PASSWORD: ${DOMO_DB_PASSWORD}
    command: ["-p", "${DOMO_DB_PORT}"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DOMO_DB_USER} -p ${DOMO_DB_PORT}"]
      interval: 3s
      timeout: 1s
      retries: 10
    depends_on:
      keycloak:
        condition: service_healthy

  # DB migrations for Domo
  domo-migrations:
    image: dzahariev/domo-migrations:1.8.6
    container_name: domo-migrations
    restart: on-failure
    environment:
      POSTGRES_HOST: domodb
      POSTGRES_PORT: ${DOMO_DB_PORT}
      POSTGRES_DB: ${DOMO_DB_NAME}
      POSTGRES_USER: ${DOMO_DB_USER}
      POSTGRES_PASSWORD: ${DOMO_DB_PASSWORD}
      POSTGRES_SSL: ${DOMO_DB_SSL}
    depends_on:
      domodb:
        condition: service_healthy
    command: ["-database", "postgres://${DOMO_DB_USER}:${DOMO_DB_PASSWORD}@domodb:${DOMO_DB_PORT}/${DOMO_DB_NAME}?sslmode=${DOMO_DB_SSL}", "-path", "/db/migrations", "up"]

  # Domo container
  domo:
    image: dzahariev/domo:1.8.6
    container_name: domo
    restart: always
    hostname:
      domo.${ROOT_HOST}
    volumes:
      - ./domo/keycloak/keycloak.json:/public/keycloak-cfg/keycloak.json:ro
    environment:
      AUTH_URL: https://auth.${ROOT_HOST}
      AUTH_REALM: ${DOMO_REALM}
      AUTH_CLIENT_ID: ${DOMO_CLIENT_ID}
      AUTH_CLIENT_SECRET: ${DOMO_CLIENT_SECRET}
      POSTGRES_HOST: domodb
      POSTGRES_PORT: ${DOMO_DB_PORT}
      POSTGRES_DB: ${DOMO_DB_NAME}
      POSTGRES_USER: ${DOMO_DB_USER}
      POSTGRES_PASSWORD: ${DOMO_DB_PASSWORD}
      POSTGRES_SSL: ${DOMO_DB_SSL}
      VIRTUAL_HOST: domo.${ROOT_HOST}
      LETSENCRYPT_HOST: domo.${ROOT_HOST}
      VIRTUAL_PORT: 8800
    depends_on:
      - domo-migrations

  # TaskBoard container
  taskboard:
    image: dzahariev/taskboard:1.25
    container_name: taskboard
    restart: always
    hostname:
      taskboard.${ROOT_HOST}
    volumes:
      - "${PLEX_MEDIA_DIR}/tasks:/tasks"
      - ./taskboard/keycloak/keycloak.json:/public/keycloak-cfg/keycloak.json:ro
      - ./taskboard/configuration.json:/tasks/configuration.json:ro
    environment:
      AUTH_URL: https://auth.${ROOT_HOST}
      AUTH_REALM: ${TASKBOARD_REALM}
      AUTH_CLIENT_ID: ${TASKBOARD_CLIENT_ID}
      AUTH_CLIENT_SECRET: ${TASKBOARD_CLIENT_SECRET}
      VIRTUAL_HOST: taskboard.${ROOT_HOST}
      LETSENCRYPT_HOST: taskboard.${ROOT_HOST}
      VIRTUAL_PORT: 8800
    depends_on:
      keycloak:
        condition: service_healthy

  # Handbrake worker container
  handbrake-worker:
    image: dzahariev/handbrake-worker:3.2
    container_name: handbrake-worker
    restart: always
    cpu_shares: 10
    volumes:
      - "${PLEX_MEDIA_DIR}/tasks:/tasks"
      - "${PLEX_MEDIA_DIR}/handbrake/input:/input"
      - "${PLEX_MEDIA_DIR}/handbrake/output:/output"
    devices:
      - /dev/dri:/dev/dri

  # DLP worker container
  dlp-worker:
    image: dzahariev/dlp-worker:1.7
    container_name: dlp-worker
    restart: always
    cpu_shares: 10
    volumes:
      - "${PLEX_MEDIA_DIR}/tasks:/tasks"
      - "${PLEX_MEDIA_DIR}/downloads:/output"

  # MariaDB container
  mariadb:
    image: mariadb:11.8.2
    container_name: mariadb
    restart: always
    volumes:
      - "${DATA_DIR}/mariadb:/var/lib/mysql"
    environment: 
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}

  # Wordpress container
  wordpress:
    image: wordpress:6.8.2
    container_name: wordpress
    restart: always
    volumes:
      - "${DATA_DIR}/wordpress:/var/www/html/"
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${MARIADB_USER}
      WORDPRESS_DB_PASSWORD: ${MARIADB_PASSWORD}
      WORDPRESS_DB_NAME: ${MARIADB_DATABASE}
      WORDPRESS_TABLE_PREFIX: "wp_"
      VIRTUAL_HOST: georgi.${ROOT_HOST}
      LETSENCRYPT_HOST: georgi.${ROOT_HOST}
    depends_on:
      - acme-companion
      - mariadb
